version: '3.8'

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/food_delivery
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=food_delivery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  celery:
    build: ./backend
    command: celery -A backend worker -l INFO
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/food_delivery
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery-beat:
    build: ./backend
    command: celery -A backend beat -l INFO
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/food_delivery
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - web

volumes:
  postgres_data: 